name: Python application

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    services:
      dynamodb:
        image: amazon/dynamodb-local
        ports:
          - 8000:8000
        options: >-
          --health-cmd "curl -s http://localhost:8000 || exit 1"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    env:
      # Make sure this region matches what your code expects or update your code accordingly.
      AWS_DEFAULT_REGION: ap-southeast-2
      DYNAMODB_ENDPOINT: http://localhost:8000
      AWS_ACCESS_KEY_ID: testing
      AWS_SECRET_ACCESS_KEY: testing
      AWS_SECURITY_TOKEN: testing
      AWS_SESSION_TOKEN: testing

    steps:
      - uses: actions/checkout@v3

      - name: Set up Python 3.10
        uses: actions/setup-python@v3
        with:
          python-version: "3.10"

      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install flake8 pytest
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

      - name: Start server
        run: python3 src/app.py &
        
      - name: Wait for server to start
        run: sleep 10

      - name: Create DynamoDB Table
        run: |
          aws dynamodb create-table \
            --table-name StockAnalytics \
            --attribute-definitions AttributeName=user_name,AttributeType=S AttributeName=stock_symbol#date,AttributeType=S \
            --key-schema AttributeName=user_name,KeyType=HASH AttributeName=stock_symbol#date,KeyType=RANGE \
            --provisioned-throughput ReadCapacityUnits=5,WriteCapacityUnits=5 \
            --endpoint-url $DYNAMODB_ENDPOINT
        env:
          AWS_DEFAULT_REGION: ${{ env.AWS_DEFAULT_REGION }}
          AWS_ACCESS_KEY_ID: testing
          AWS_SECRET_ACCESS_KEY: testing

      - name: Lint with flake8
        run: |
          flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
          flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics

      - name: Run tests with coverage
        run: |
          coverage run --source . --omit=src/app.py -m pytest
          coverage report -m --fail-under=85
